# Generated by Django 2.0.1 on 2018-01-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
